
name: keepalive_kyb

on:
  schedule:
    # 每隔7天运行一次，运行时间点自行设置(此处北京时间8:30运行)
    - cron: '30 0 */7 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Keepalive
      run: python3 koyeb.py
      env:
        KOY_EB: ${{ secrets.KOY_EB }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}  ## 填写对应的平台通知变量名[此处使用企业微信应用消息推送]，若需要多平台同时推送，请按此格式填写多个平台对应的变量名即可
